Update bunnyshell.yaml
Signed-off-by: mihaichitic <m.chitic+github@gmail.com>

diff --git a/.bunnyshell/templates/preview/bunnyshell.yaml b/.bunnyshell/templates/preview/bunnyshell.yaml
--- a/.bunnyshell/templates/preview/bunnyshell.yaml
+++ b/.bunnyshell/templates/preview/bunnyshell.yaml
@@ -226,23 +226,25 @@ components:
                 && kubectl wait deployment -n {{ env.k8s.namespace }} ttyd --for condition=Available=True --timeout=30s \
                 && sleep 30 # time to for ttyd to finish starting
             - |
+                echo "settings readonly-user pass ..." \
+                && kubectl exec deployment/ttyd -c ttyd -n {{ env.k8s.namespace }} -- /bin/bash -c " \
+                   argocd account update-password \
+                   --account readonly-user \
+                   --current-password ${ARGOCD_ADMIN_PASS} \
+                   --new-password ${ARGOCD_READONLY_PASS} \
+                   || echo \"❗ Could not set readonly-user password\" "
+            - |
                 echo "adding demo app ..." \
                 && kubectl exec deployment/ttyd -c ttyd -n {{ env.k8s.namespace }} -- /bin/bash -c " \
-                   argocd app create guestbook \
+                   argocd app create guestbook-{{ env.unique }} \
                    --repo https://github.com/argoproj/argocd-example-apps.git \
                    --path guestbook \
                    --dest-server https://kubernetes.default.svc \
                    --insecure \
                    --dest-namespace {{ env.k8s.namespace }}-guestbook \
                    --sync-option CreateNamespace=true \
-                   && argocd app sync guestbook"
-            - |
-                echo "settings readonly-user pass ..." \
-                && kubectl exec deployment/ttyd -c ttyd -n {{ env.k8s.namespace }} -- /bin/bash -c " \
-                   argocd account update-password \
-                   --account readonly-user \
-                   --current-password ${ARGOCD_ADMIN_PASS} \
-                   --new-password ${ARGOCD_READONLY_PASS}"
+                   && argocd app sync guestbook-{{ env.unique }} \
+                   || echo \"❗ Could not sync guestbook app\" "
         destroy:
             - |
                 echo "checking argocd is up ..." \
